config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

    resources :posts
    get '/posts/new', to: 'posts#new', as: 'post_new'
    get '/posts', to: 'posts#index', as: 'post_all'
    
    resources :users
    get '/users', to: 'users#index', as: 'user_all'
    get '/perfil/:id', to: 'users#show', as: 'user_perfil'
    get '/perfil/edit/:id', to: 'users#edit', as: 'user_edit'

    resources :friendships
    get'/follow/:id', to: 'friendships#create', as: 'follow'
    get'/unfollow/:id', to: 'friendships#destroy', as: 'unfollow'

    root 'home#show'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

    # User 1 -> n Post
    has_many :posts
    
    # User n -> n Friendships n <- n User
    has_many :friendships
    has_many :friends, :through => :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user
    
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.password = Devise.friendly_token[0,20]
            user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    helper_method :current_user
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:destroy]

  # POST /friendships
  # POST /friendships.json
    def create
        @friendship = current_user.friendships.build(:friend_id => params[:id])
        
        if @friendship.save
            flash[:notice] = "Added friend."
            redirect_to root_path
        else
            flash[:error] = "Unable to add friend."
            redirect_to root_path
        end
    end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
    def destroy
        @friendship = Friendship.find(params[:id])
        @friendship.destroy
        
        flash[:notice] = "Removed friendship."
        redirect_to root_path
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
        @friendship = Friendship.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
        if user_signed_in?
            @posts = Post.where('posts.user_id in
                                    (select friend_id
                                        from friendships as f, users as u
                                        where u.id = f.user_id and u.id = ?)', current_user.id)
        else
            @posts = Post.all
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action  :authenticate_user!, :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
        if user_signed_in?
            @posts = current_user.posts
        else
            @posts = Post.all
        end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
        @post = Post.new
    end

    # GET /posts/1/edit
    def edit
        @post = Post.find(params[:id])
        if @post.user_id != current_user.id
            flash[:notice] = "You can not do this!!!"
            redirect_to root_path
        end
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id

        respond_to do |format|
            if @post.save
                format.html { redirect_to @post, notice: 'Post was successfully created.' }
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { render :show, status: :ok, location: @post }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @my_posts = @user.posts
        @my_friends = @user.friends
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        respond_to do |format|
            if @user.update(user_params)
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { render :show, status: :ok, location: @user }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def user_params
        params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/show.html.erb
<div class="row">
    <% @posts.each do |post| %>
        <% user = User.find(post.user_id) %>
        <div class="col s6">
            <div class="card blue-grey lighten-5">
                <div class="card-content black-text">
                    <span class="card-title"><%= user.name %>: <%= post.title %></span>
                    <p>
                        <strong>Description:</strong>
                        <%= post.description %>
                    </p>
                </div>
                <div class="card-action">
                    <div class="row">
                        <div class="col">
                            <%= link_to 'Edit', edit_post_path(post) %>
                        </div>
                        <div class="col right">
                            <%= link_to 'Show', post %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Tuviter</title>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
    <%= javascript_include_tag 'init' %>
    <%= csrf_meta_tags %>
</head>
<body>
    
    <div class="navbar-fixed">
        <% if user_signed_in? %>
            <ul id="user-options" class="dropdown-content">
                <li><%= link_to "Perfil", user_perfil_path(current_user) %></li>
                <li><%= link_to "List of Users", user_all_path %></li>
                <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
            <ul id="user-options-side" class="dropdown-content">
                <li><%= link_to "Perfil", user_perfil_path(current_user) %></li>
                <li><%= link_to "List of Users", user_all_path %></li>
                <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
        <% end %>
        <ul id="post-options" class="dropdown-content">
            <li><%= link_to "New Post", post_new_path %></li>
            <li><%= link_to "My Posts", post_all_path %></li>
        </ul>
        <ul id="post-options-side" class="dropdown-content">
            <li><%= link_to "New Post", post_new_path %></li>
            <li><%= link_to "My Posts", post_all_path %></li>
        </ul>
        <nav class="blue-grey">
            <div class="nav-wrapper">
                <a href="/" class="brand-logo center">Tuviter</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <% if user_signed_in? %>
                        <li><a class="dropdown-button" href="#!" data-activates="post-options">Post<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="user-options"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
                    <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
                <ul class="side-nav" id="mobile-demo">  
                    <% if user_signed_in? %>
                        <li><a class="dropdown-button" href="#!" data-activates="user-options-side"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="post-options-side">Post<i class="material-icons right">arrow_drop_down</i></a></li>
                    <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav>
    </div>
    
    <div class="container">
        <meta http-equiv="refresh" content="30">
        <div class="notice"><%= notice %></div>
        <div class="alert"><%= alert %></div>

        <%= yield %>
    </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
                <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>

    <div class="card-action">
        <div class="row rignt">
            <button class="btn waves-effect waves-light right" type="submit" name="action">
                <%= f.submit %>
            </button>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
    <div class="col s11">
        <div class="card blue-grey lighten-5">
            <div class="card-content black-text">
                <span class="card-title">Editing Post</span>
                    <%= render 'form' %>
            </div>
        </div>
    </div>
    <div class="col s1">
        <div class="col s1 m1 bottom">
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large waves-effect waves-light blue-grey darken-4">
                    <i class="material-icons">settings</i>
                </a>
                <ul>
                    <li><a class="btn-floating blue-grey darken-3" href="/posts/<%= @post.id %>"><i class="material-icons">description</i></a></li>
                    <li><a class="btn-floating blue-grey darken-2" href="<%= posts_path %>"><i class="material-icons">list</i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="row">
    <div class="col s12">
        <div class="card blue-grey lighten-5">
            <div class="card-content black-text">
                <span class="card-title">Listing Posts</span>
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @posts.each do |post| %>
                            <tr>
                                <td><%= post.title %></td>
                                <td><%= post.description %></td>
                                <td><%= link_to 'Show', post %></td>
                                <td><%= link_to 'Edit', edit_post_path(post) %></td>
                                <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="card-action">
                <div class="row rignt">
                    <%= link_to 'New Post', new_post_path %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="row">
    <div class="col s11">
        <div class="card blue-grey lighten-5">
            <div class="card-content black-text">
                <span class="card-title">New Post</h1>
                <%= render 'form' %>
            </div>
        </div>
    </div>
    <div class="col s1">
        <div class="col s1 m1 bottom">
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large waves-effect waves-light blue-grey darken-4"  href="<%= posts_path %>">
                    <i class="material-icons">keyboard_return</i>
                </a>
            </div>
        </div>
    </div>
</div>   

app/views/posts/show.html.erb
<div class="row">
    <div class="col s12">
        <div class="card blue-grey lighten-5">
            <div class="card-content black-text">
                <span class="card-title"><%= @post.title %></span>
                <p>
                  <%= @post.description %>
                </p>
            </div>
            <div class="card-action">
                <div class="row">
                    <div class="col">
                        <%= link_to 'Edit', edit_post_path(@post) %>
                    </div>
                    <div class="col right">
                        <%= link_to 'Back', posts_path %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="row">
    <div class="col s12 m6">
        <div class="card blue-grey lighten-5">
            <div class="card-content black-text">
                <%= form_for (@user) do |f| %>
                    <span class="card-title">Edit <%= @user.name%></span>

                    <div class = "field">
                        <%= f.label 'Nome'%>
                        <%= f.text_field :name%>
                    </div>

                    <div class="card-action">
                        <div class="row">
                            <div class="col">
                                <%= link_to "Account Settings", edit_user_registration_path %>
                            </div>
                            <div class="col rignt">
                                <button class="btn waves-effect waves-light right" type="submit" name="action">
                                    <%= f.submit "Update" %>
                                </button>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
    <% @users.each do |user| %>
        <% if user != current_user %>
            <div class="col s4">
                <div class="card blue-grey lighten-5">
                    <div class="card-content black-text">
                        <span class="card-title"><%= user.name %></span>
                        <p>
                            <strong>Email:</strong>
                            <%= user.email %>
                        </p>
                    </div>
                    <div class="card-action">
                        <div class="row">
                            <div class="col">
                                <% friendship = Friendship.where(:user_id => current_user.id, :friend_id => user.id) %>
                                <% if friendship.empty? %>
                                    <%= link_to "Follow", follow_path(user) %>
                                <% else %>
                                    <%= link_to "Unfollow", unfollow_path(friendship.first) %>
                                <% end %>
                            </div>
                            <div class="col rignt">
                                <%= link_to "Show", user_perfil_path(user) %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col s8">
        <div class="row">
            <div class="col s12">
                <div class="card blue-grey lighten-3">
                    <div class="card-content black-text">
                        <span class="card-title"><%= @user.name %></span>
                        <p>
                            <strong>Email:</strong>
                            <%= @user.email %>
                        </p>
                    </div>
                    <div class="card-action">
                        <%= link_to "Edit", user_edit_path(@user) %>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <% @my_posts.each do |post| %>
                <div class="col s6">
                    <div class="card blue-grey lighten-5">
                        <div class="card-content black-text">
                            <span class="card-title"><%= post.title %></span>
                            <p>
                                <strong>Description:</strong>
                                <%= post.description %>
                            </p>
                        </div>
                        <div class="card-action">
                            <div class="row">
                                <div class="col">
                                    <%= link_to 'Edit', edit_post_path(post) %>
                                </div>
                                <div class="col right">
                                    <%= link_to 'Show', post %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="col s4">
        <% @my_friends.each do |friend| %>
            <div class="row">
                <div class="card blue-grey lighten-4">
                    <div class="card-content black-text">
                        <span class="card-title"><%= friend.name %></span>
                        <p>
                            <strong>Email:</strong>
                            <%= friend.email %>
                        </p>
                    </div>
                    <div class="card-action">
                        <div class="row">
                            <% friendship = Friendship.where(:user_id => @user.id, :friend_id => friend.id).first %>
                            <div class="col">
                                <%= link_to "Unfollow", unfollow_path(friendship) %>
                            </div>
                            <div class="col rignt">
                                <%= link_to "Show", user_perfil_path(friendship.friend_id) %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>